# Generated by Django 5.0.1 on 2024-05-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imgTitl', models.ImageField(upload_to='projectPhoto')),
                ('imgDetalone', models.ImageField(upload_to='projectPhoto')),
                ('imgDetalTwo', models.ImageField(upload_to='projectPhoto')),
                ('imgDetalThree', models.ImageField(upload_to='projectPhoto')),
                ('description', models.TextField(max_length=1000)),
                ('date', models.DateField()),
                ('Categroy', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=1000)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
